INSERT INTO TB_TANQUES(DESCRICAO, TIPO) VALUES('Tanque 1', 0);
INSERT INTO TB_TANQUES(DESCRICAO, TIPO) VALUES('Tanque 2', 1);

INSERT INTO TB_BOMBAS(DESCRICAO, ID_TANQUE) VALUES('Bomba 1', 0);
INSERT INTO TB_BOMBAS(DESCRICAO, ID_TANQUE) VALUES('Bomba 2', 0);
INSERT INTO TB_BOMBAS(DESCRICAO, ID_TANQUE) VALUES('Bomba 1', 1);
INSERT INTO TB_BOMBAS(DESCRICAO, ID_TANQUE) VALUES('Bomba 2', 1);

INSERT INTO TB_CONFIGURACAO(VALOR_LITRO_GASOLINA, VALOR_LITRO_DIESEL, VALOR_IMPOSTO)VALUES(6.10, 5.96, 13.00);


